.travis.yml
inspire_query_parser/parser.py
inspire_query_parser/utils/parse_tree_formatter.py

global: add .travis.yml

---

.travis.yml

travis: add automatic PyPI deployment

---

inspire_query_parser/parser.py
inspire_query_parser/stateful_pypeg_parser.py
tests/test_parser.py

parser: make stateful parser's flags private

---

setup.py

Otherwise [this](https://travis-ci.org/inspirehep/inspire-query-parser/jobs/262273607#L676) happens (which is currently preventing me from cutting a `0.1.0` release).

setup: fix classifiers

---

inspire_query_parser/visitors/restructuring_visitor.py
tests/test_restructuring_visitor.py

_This PR is branched off the driver module PR._

Flatten eagerly identified NestedKeywordQuery

---

inspire_query_parser/parsing_driver.py
tests/test_parsing_driver.py

* Add try-catch-all exception handling for visitors, so that search
never fails for the user. In case of error, a multi_match query is
generated using the query_str argument for the query value.

driver: add catch-all exc. handling for visitors

---

inspire_query_parser/visitors/elastic_search_visitor.py

elasticsearch_visitor: handle more keywords

---

inspire_query_parser/config.py
inspire_query_parser/parser.py
tests/test_parser_functionality.py

parser: recognize mixed case keywords

---

inspire_query_parser/parsing_driver.py
inspire_query_parser/stateful_pypeg_parser.py

* Convert `query_str` to unicode at system's boundary.

driver: convert query_str to unicode

---

inspire_query_parser/parsing_driver.py

driver: fix logging format on exceptions

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

* Add support for querying multiple fields. This is achieved by either
using the `multi_match` query (simple value case), or `query_string`
by employing the `fields` field, or with multiple `should` `bool`
queries for the case of exact matches.

Add multi fields support

---

examples/demo_parser.py
inspire_query_parser/parsing_driver.py
inspire_query_parser/stateful_pypeg_parser.py

stateful_parser: remove module level parse method

---

inspire_query_parser/config.py

config: add field-code keyword

---

inspire_query_parser/visitors/elastic_search_visitor.py

Update `reportnumber` field mapping to the fuzzy analyzed field.

es_visitor: update `reportnumber` field mapping

---

inspire_query_parser/visitors/elastic_search_visitor.py

es_visitor: add type-code fieldname mapping

---

inspire_query_parser/utils/visitor_utils.py
tests/test_restructuring_visitor.py

utils: fix yesterday date specifier handling

---

inspire_query_parser/parser.py

* Use more descriptive names for return values of PyPEG parse method.

parser: use more descriptive variable names

---

inspire_query_parser/config.py
tests/test_restructuring_visitor.py

config: update texkey mapping

---

inspire_query_parser/visitors/elastic_search_visitor.py

es_visitor: add author-count fieldname mapping

---

inspire_query_parser/visitors/elastic_search_visitor.py

es-visitor: make keyword mapping a class member

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

NEW: Add support for BAI author queries, which are generated when an
author keyword is detected and either the value of the node matches the
BAI pattern which queries only the BAI field, or the value contains a
dot and no whitespace (i.e. author name), which queries both authors
name and BAI fields.
This implements a behaviour like this:
If we have a keyword query, whose keyword is `author`:
- either query only the BAI ElasticSearch field, if BAI pattern matches.
- or query both BAI and authors `full_name` fields, if no whitespace and dot exist in the value of the node.
We can see how this behaves and if we're missing out results, then we can fallback to _always query on both fields_.

es-visitor: add support for BAI

---

setup.py

global: bump inspire-utils to 1.0.0

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

es-visitor: use re.search to check for whitespace

---

inspire_query_parser/config.py

config: set bb, bull keywords mapping to eprint

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

Signed-off-by: Szymon Łopaciuk <szymon@lopaciuk.eu>

elastic_search_visitor: wildcard nest only authors

---

setup.py

Signed-off-by: Harris Tzovanakis <me@drjova.com>
Sem-Ver: breaks compatibility

setup: bump the vesrion

---

inspire_query_parser/utils/visitor_utils.py
inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py
tests/test_visitor_utils.py

Added nested to elastic search query for nested fields

---

inspire_query_parser/utils/visitor_utils.py
setup.py

sem-ver: breaks compatibility
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>

bump inspire-utils and inspire-schemas version

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

Signed-off-by: Harris Tzovanakis <me@drjova.com>

refersto: change path

---

setup.py

Signed-off-by: Micha Moskovic <michamos@gmail.com>
Sem-Ver: breaks compatibility

setup: bump inspire-schemas to v60.*

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

* Added a check that collection is Literature for the refersto
* INSPIR-2477

Add a check that collection is Literature for the refersto

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

es_visitor: Add legacy compatible typecodes

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

es_visitor: remove self citations from refersto

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

Signed-off-by: Harris Tzovanakis <me@drjova.com>

visitor: remove NotImplementedError

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

Change to ``must`` between the different names
``a john k. ellis``
``K`` **match** ``first_name.initials`` **AND** ( ``ellis`` **prefix** ``first_name`` **OR** ``e`` match ``first_name``)

authors: make queries AND between their names

---

inspire_query_parser/utils/visitor_utils.py
inspire_query_parser/visitors/elastic_search_visitor.py
setup.cfg
tests/test_elastic_search_visitor.py

affiliations: add nested queries support

---

inspire_query_parser/visitors/elastic_search_visitor.py
setup.py
tests/test_elastic_search_visitor.py

es_visitor: support for legacy jhep/jcap queries

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

visitor: fix wildcard search with dots

---

inspire_query_parser/config.py
inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

first_author: add support for first author

---

inspire_query_parser/config.py
inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

affiliations-id: add support for affiliations-id

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

visitor: add texkey search

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

refersto: add refersto author

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

visitor: more precise pattern matches for texkey

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

* INSPIR-3452
* The reason for switching from query string query to wildcard query is that in the latter the only special characters are \* and \?, so slash wouldn't cause syntax error

visitor: enable wildcard queries with slash

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

visitor: don't use term queries for exact mach queries in authors

---

inspire_query_parser/utils/visitor_utils.py
inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

visitor: add escaping support for special characters in query_string query

---

inspire_query_parser/config.py
inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

visitor: support range queries in publication_info.year

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

visitor: support range queries for date-added and date-updated

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

visitor: wrap queries in nested query when fieldnames are nested

---

inspire_query_parser/parser.py
tests/test_elastic_search_visitor.py
tests/test_parser.py
tests/test_parser_functionality.py
tests/test_restructuring_visitor.py

* Ref inspirehep/inspirehep#1239.

parser: remove implicit `and` for SPIRES-style

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

Ref: inspirehep/inspirehep#1472

visitor: use proper queries for complex queries without keyword

---

inspire_query_parser/config.py
tests/test_elastic_search_visitor.py

Ref: inspirehep/inspirehep#1634

config: add primarch search

---

inspire_query_parser/config.py
inspire_query_parser/parser.py
inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py
tests/test_parser.py
tests/test_restructuring_visitor.py

Ref: inspirehep/inspirehep#1791

parser: change arxiv handling

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

ref: inspirehep/inspirehep#2066

es visitor: use and operator for wildcard query strings

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

ref: inspirehep/inspirehep#2222

es visitor: fix partial match queries

---

.github/workflows/build-and-release.yml
inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

ref: inspirehep/inspirehep#2345

es visitor: de should be range query

---

inspire_query_parser/utils/visitor_utils.py
inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

Ref: https://github.com/inspirehep/inspirehep/issues/2448

Able to search * journal titles

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

remove publication_info.year

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

Ref: https://github.com/inspirehep/inspirehep/issues/2448

add journal_title to ```j``` queries that contain ```*```

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

ref: https://github.com/inspirehep/inspirehep/issues/2437

add fulltext field

---

inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py

ref: cern-sis/issues-inspire#102

es visitor: add citedby keyword & terms lookup

---

.github/workflows/build-and-release.yml
inspire_query_parser/config.py
inspire_query_parser/visitors/elastic_search_visitor.py
tests/test_elastic_search_visitor.py
tests/test_restructuring_visitor.py

ref: cern-sis/issues-inspire#235

fix texkey query

---

.github/workflows/pull-request.yml
.github/workflows/push-master.yml
.github/workflows/test.yml
setup.py

* ref https://github.com/cern-sis/issues-inspire/issues/863

gh-actions: adapt pipelines

---

.github/workflows/bump-and-publish.yml
.github/workflows/lint.yml
.github/workflows/pull-request.yml
.github/workflows/push-master.yml
.github/workflows/test.yml
setup.py

ref: https://github.com/cern-sis/issues-inspire/issues/868

upgrade dependencies for py3.11
