- inspire_query_parser/parser.py
- pytest.ini
- setup.py
- tests/conftest.py
- tests/helpers/test_utils.py
- tests/test_parser.py
* Add custom parametrize in tests/helpers. Use sys.path append hack for
using it at tests.
* Add tests for plaintext parsing:
* SimpleValueUnit parse and parse_terminal_token methods
* SimpleValue parse method
* Refactor parse_terminal_token with clearer variable names and allow
SimpleValue `__init__` to accept text_type for making it testable.
> tests: add custom parametrize and terminals tests

- inspire_query_parser/ast.py
- inspire_query_parser/config.py
- inspire_query_parser/parser.py
- inspire_query_parser/stateful_pypeg_parser.py
- inspire_query_parser/utils/format_parse_tree.py
- inspire_query_parser/utils/utils.py
- tests/helpers/test_utils.py
- tests/test_format_parse_tree.py
- tests/test_parser.py
* parser: Add convert input to unicode at current entrypoint (parse
method).
* format_parse_tree: Use unicode literals and assume input is unicode.
* tests: Add test for format_parse_tree module (handling of unicode).
* ast: Bug-fix ast.ListOp.__eq__ implementation checking for op field.
* parser: Add __init__ for LeafRule, UnaryRule and BinaryRule for being
able to instantiate a parse tree in tests.
> global: refactoring & convert to unicode @ parse

- demo_parser.py
- inspire_query_parser/parser.py
* Make GreaterEqualOp and LessEqualOp stricter:
* Make recognition of number(s){-,+} format stricter, i.e. don't accept
whitespace between number and symbols.
* Remove rule for accepting everything that isn't a whitespace and
accept number or numbers separated by (/,-) symbols.
These changes aim to eliminate ambiguity with (-,+) symbols, among
boolean queries and GE/LE values.
> parser: GE/LE bug-fix in "number{-,+}" recognition

- inspire_query_parser/__init__.py
- inspire_query_parser/parsing_driver.py
- inspire_query_parser/visitors/__init__.py
- inspire_query_parser/visitors/elastic_search_visitor.py
- inspire_query_parser/visitors/restructuring_visitor.py
- setup.py
- tests/test_elastic_search_visitor.py
- tests/test_parsing_driver.py
Adds the driver module, which will be used by Inspire-next. 
_This PR is branched off the ElasticSearchVisitor PR._
> global: add driver implementation (public API)

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_restructuring_visitor.py
* Integrates inspire-next query parser related tests, so that it is
documented that they are now working.
* Add refersto ES field name mapping in ElasticSearch visitor.
> tests: integrate inspire-next tests

- inspire_query_parser/config.py
- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
- tests/test_restructuring_visitor.py
* Handle Value, PartialMatch and ExactMatch queries (i.e. not as values
but as queries, e.g. 'ellis, j')
* Add more ElasticSearch fieldnames for the demo.
> elasticsearch_visitor: handle value queries

- inspire_query_parser/parsing_driver.py
* Use logger.exception so that stacktrace information is available on
Sentry.
Fixes https://sentry.cern.ch/inspire-sentry/inspire-labs/group/865574/ and  https://sentry.cern.ch/inspire-sentry/inspire-labs/group/865575/.
> driver: use logger.exception on visitor errors

- inspire_query_parser/parser.py
- tests/test_parser_functionality.py
- tests/test_restructuring_visitor.py
* Improve SimpleValueBooleanQuery parsing by being more explicit on
what rules we accept as right operands. (fixes #18)
> parser: improve SimpleValueBooleanQuery parsing

- inspire_query_parser/config.py
- inspire_query_parser/parser.py
- tests/test_parser.py
- tests/test_restructuring_visitor.py
* Ignore `arxiv:` prefix of simple value tokens, since our our data
don't contain it.
* Make `eprint` keyword resolve to `eprint` and not `reportnumber`.
> parser: ignore `arxiv:` prefix of simple values

- inspire_query_parser/visitors/elastic_search_visitor.py
- inspire_query_parser/visitors/restructuring_visitor.py
- tests/test_restructuring_visitor.py
* Do not convert `NestedKeywordQuery` to `KeywordOp` query when value
is a `ValueQuery`.
* Fix `doi` keyword mapping to an ElasticSearch field name.
> restructuring_visitor: remove flattening of nested keyword query

- inspire_query_parser/__init__.py
- inspire_query_parser/stateful_pypeg_parser.py
- inspire_query_parser/visitors/restructuring_visitor.py
- pytest.ini
- tests/test_elastic_search_visitor.py
You unfortunately copied the configuration of INSPIRE before I managed to clean most of the errors, which meant you had ignores for things that shouldn't be ignored. Check the configuration today: https://github.com/inspirehep/inspire-next/blob/096666d85a2232f1f58692831b288ffaa78d3a16/pytest.ini#L25
In particular, we want to ignore `E501` (line length), but we don't want to ignore the others. The `FI` ones check the `__future__` imports, which are not uniform in this project, but are used correctly AFAICT. The only serious one is `F401`. See for example https://github.com/inspirehep/inspire-next/pull/2708 to see what kind of errors it can hide.
> tests: restrict flake8 ignores to what is needed

- setup.py
The previous version of ``pytest-flake8`` was incompatible with the
latest version of ``flake8``, so we bump the former.
Closes https://github.com/inspirehep/inspire-query-parser/pull/39.
> setup: bump pytest-flake8

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
* Fix range queries with multiple fields.
* Add more fieldname mappings for 'date' keyword.
* _generate_query_string will not generate an 'analyze_wildcard' under
'query_string' if the flag is set to False, since this is the default
behaviour.
> es-visitor: fix range queries with multiple-fields

- inspire_query_parser/visitors/elastic_search_visitor.py
The fieldname mapping `inspire_categories.term` is analyzed, although
for this kind of search we want it to be not analyzed.
@jacquerie 
Do you think using `facet_*` field is ok? 
Or should I create in the hep mapping, under `inspire_categories`, another child field called `raw` with `"index": "not_analyzed"`?
> es_visitor: update `subject` fieldname mapping

- inspire_query_parser/parser.py
- inspire_query_parser/stateful_pypeg_parser.py
- tests/test_parser_functionality.py
- tests/test_restructuring_visitor.py
* Add support for texkey queries (special case for its values, since a
':' symbol needs to be accepted - not the usual case).
> parser: add texkey support

- inspire_query_parser/visitors/elastic_search_visitor.py
- setup.py
- tests/test_elastic_search_visitor.py
Use ES range query for supporting any type of range queries (bounded or unbounded).
> es_visitor: refactor multi-field range queries

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
- tests/test_parsing_driver.py
Handle author search as a special case, by generating author's name
variations (from inspire-utils) along with a match query on author's
full_name. This helps with imitating legacy's more "exact" search.
Depends on https://github.com/inspirehep/inspire-utils/pull/18 to be merged and deployed to PyPi.
> es_visitor: specialized author search

- inspire_query_parser/config.py
- tests/test_restructuring_visitor.py
Map `recid` to `control_number`, while also adding a keyword mapping for `control_number` (Adresses https://github.com/inspirehep/inspire-query-parser/issues/57).
Signed-off-by: Iuliana Voinea <iuliana.voinea@student.manchester.ac.uk>
> config: change `recid` mapping

- inspire_query_parser/ast.py
- inspire_query_parser/visitors/elastic_search_visitor.py
- inspire_query_parser/visitors/restructuring_visitor.py
- tests/test_restructuring_visitor.py
This is towards more consistency to the `AST` naming scheme:
- Firstly, renaming `ValueQuery` to `ValueOp`, so as to follow the same convention with `KeywordOp` (they have the "level" semantics in the parse tree hierarchy).
- Wrap all `Value`s _(that are not part of keyword queries)_ with `ValueOp` nodes, in order to have uniform handling for nodes of the same hierarchy (also, for readability).  
For example, we have `NotOp(KeywordOp(Keyword('author'), Value('ellis')))` and we **had** `NotOp(Value('ellis'))`. The latter one is now transformed into `NotOp(ValueOp(Value('ellis')))`.
> rst-visitor: wrap Value with ValueOp

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
Use ``"operator": "and"`` in ``match`` queries for making sure that if
multiple words are provided, they all must show up in the queried field
(addresses inspirehep/inspire-next#3048).
This was motivated due to `title` queries (inspirehep/inspire-next#3048), but also matches our goals for "more exact" (similar to legacy) results.
Branched off from #67.
> es-visitor: `"operator": "and"` in `match` queries

- inspire_query_parser/config.py
- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
I added functionality to the es-visitor that supports `irn` simple value queries,
i.e. for SPIRES identifiers. There is no need to support this kind of query
with partial or exact values, as they are only made by the system and not by users,
always having this expected layout.
Closes https://github.com/inspirehep/inspire-query-parser/issues/65
https://github.com/inspirehep/inspire-next/pull/3058
It is needed for the inspire_query_parser to support `irn`(term) queries.
This is supported by Legacy.
Signed-off-by: Iuliana Voinea <iuliana.voinea@student.manchester.ac.uk>
> es-visitor: support `irn` simple value queries

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
Checking for partial BAI should happen on a normalized author name, so
that we can make the code that detects it simpler, without adding more
special cases (addresses inspirehep/inspire-next#3055).
> es-visitor: check partial BAI on normalized name

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
Strip ':' from malformed query words which are feeded to a query_string
and thus making ElasticSearch fail when trying to parse them as fields
(addresses #66).
> es-visitor: strip ':' from malfomed query words

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
- tests/test_restructuring_visitor.py
I added functionality to the es-visitor that supports `exact-author` queries, i.e. when someone writes a query of the form `ea Ellis, J`, or any other acceptable variation of `exact-author`, the visitor will check whether the value is a bai. Then, it will perform a `term` query on the appropriate field, `authors.full_name.raw` for author names and `authors.ids.value` for bais. These fields are not analysed, therefore the probablility of an exact match is high, as both the indexed value and the queried value are normalized by the same normalizers that Inspire uses, and no ES specific normalizer or filter is applied, thus the entire author name/bai is indexed as a single term.
https://github.com/inspirehep/inspire-query-parser/issues/63
https://github.com/inspirehep/inspire-next/pull/3064 …
> es-visitor: support exact-author queries

- inspire_query_parser/parsing_driver.py
- inspire_query_parser/utils/visitor_utils.py
- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
- tests/test_parsing_driver.py
- tests/test_visitor_utils.py
Rewrite of date queries (closes #73):
* Converts mutli-field range queries to a chain of bool.should clauses
so that if a field doesn't exist in a record, the query will still
produce results. Same processing happens for date range queries.
* Date queries with equality and Value or Partial value are transformed
into range queries, starting from the given date and up to the next
date (according to the granularity of the date typed by the user).
* Uses PartialDate from inspire-utils, so that it drops all given date
parts except for the year, for fields that only contain a year
(otherwise the query in ES errors out).
* Add simple support for wildcard operator in simple and partial match
value date queries. The policy followed is:
* if the whole date part is a wildcard, then we ignore it and …
> es-visitor: rewrite date queries

- inspire_query_parser/utils/visitor_utils.py
- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
- tests/test_parsing_driver.py
- tests/test_visitor_utils.py
~This is a WIP PR for tracking the progress of improving authors searching.~
Improves author search by making it more conservative on what records
it returns (more like legacy) (addresses inspirehep/inspire-next#3055).
For this, we employ two different kind of queries:
- If the given author name parts are all in full (i.e. no initials, or
not only lastnames), then we generate minimal name variations in
order to match with the broader ones (during index time).
Additionally, in this case, we require for the fullname, to matches
all the provided name parts. Thus, being able to filter out authors
with same lastname and similar prefix firstnames (e.g. 'Mele,
Salavtore' and 'Mele, Samuele').
- Otherwise, on initials or lastnames only, fallback to filtering only
with the minimal name variations.
> es-visitor: improve authors search

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
The type-code query requires a special way of hanlding it, as in
depending on the value of the type-code query, we query another field
in accordance to the `TYPECODE_VALUE_TO_FIELD_AND_VALUE_PAIRS_MAPPING`.
Even if the value of the query is an exact, or partial value then it is
handled in the same way as a simple value (closes #79).
> es-visitor: add support for type-code queries

- inspire_query_parser/utils/visitor_utils.py
- tests/test_restructuring_visitor.py
{Last, this} month date specifiers now respect the current day while
doing the other transformations as usual. E.g. last month - 2, if done
on the date of this commit, will be transformed to a date query with
value 2017-12-24 (closes #85).
> rst-visitor: {last, this} month respect current day

- inspire_query_parser/utils/visitor_utils.py
- inspire_query_parser/visitors/elastic_search_visitor.py
- inspire_query_parser/visitors/restructuring_visitor.py
- setup.py
- tests/test_elastic_search_visitor.py
- tests/test_restructuring_visitor.py
- tests/test_visitor_utils.py
* es-visitor: add support for journal queries on journal title, journal
volume and artid/page start.
* restructuring-visitor: implement `journal and vol` query support and
drop the `vol` part of `journal and not vol` queries.
* setup: depend on `inspire-schemas`, since we require `convert_old_publication_info_to_new`.
For that reason, `inspire-utils` is dropped as a dependency, in place of `inspire-schemas`.
* `convert_old_publication_info_to_new` of `inspire-schemas` is used
for supporting journal keyword queries.
* Use `convert_old_publication_info_to_new` of `inspire-schemas` to
preprocess and validate the searched values, i.e. the journal_title,
journal_volume and artid/page_start.
* utils: add generic functions for generating nested, match
and bool queries.
* Ensure journal queries …
> Add journal nested queries support

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
Make exact author queries nested in order to be compatible with the 'author' field which has been changed to nested.
Signed-off-by: Iuliana Voinea <iulianavoinea96@gmail.com>
> elastic_search_visitor: nested exact author queries

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
Make author queries nested in order to be compatible with the 'authors' field which has been changed to nested.
Signed-off-by: Iuliana Voinea <iulianavoinea96@gmail.com>
> elastic_search_visitor: nested author queries

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
Make all special cases (bai value, regex, exact value, partial value, wildcard ...etc) author queries nested in order to be compatible with the 'authors' field which has been changed to nested.
Signed-off-by: Iuliana Voinea <iulianavoinea96@gmail.com>
> elastic_search_visitor: all author queries nested

- inspire_query_parser/utils/visitor_utils.py
- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
- tests/test_visitor_utils.py
Handle unknown keyword searches (especially caused by texkey freetext searches or invenio syntax searches with keywords that are not inspire parser keywords). Instead of just querying the given field for the value found after the `:`, now we do a `dis_max` query that will contain the given field query + a query that searches `_all` for the entire value of the form `keyword:value`. This way, users can now look for texkeys using freetext, and still get results.
Signed-off-by: Iuliana Voinea <iulianavoinea96@gmail.com>
> elastic_search_visitor: handle unknown fieldnames

- inspire_query_parser/visitors/elastic_search_visitor.py
- setup.cfg
- tests/test_elastic_search_visitor.py
INSPIR-1486 
Changed the ea bai query to use the authors ids search field instead of the raw field.
> Added search for ea bai using lowercase

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
Added special query for affiliations
> Add aff query

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
So that elastic search won't throw an error.
> use simple_query_string for malformed queries

- inspire_query_parser/config.py
- inspire_query_parser/parser.py
- inspire_query_parser/stateful_pypeg_parser.py
- inspire_query_parser/utils/visitor_utils.py
- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
- tests/test_parser.py
Several changes to the query parser:
* Values with colons inside are now handled for all keywords. This was not handled previously due to the ambiguity in `key foo bar:baz`. Is it a search for `foo bar:baz` in `key` or a search for `foo` in `key` and `baz` in `bar`? To handle this, colons are allowed only in the first space-separated value. As a side-effect, this allowed to remove the special-casing for texkey searches.
* Exact matches are delimited by `"..."`. This was previously translated into a `term` query (for most fields), which is useless for `text` fields as the search query needs to match exactly the output of the analyzer. Now a `match_phrase` is used, which should work correctly.
* Search for creation, update and earliest dates are now handled correctly.
* Makes the searching …
> Fix PDG search

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
This is will fix the problem when you search ``a Lian-Tao Foo``
will search ``Lian-Tao Foo`` in firstname **OR** (``L`` in first name **AND** ``T`` in firstname) to avoid having results from just ``L Foo`` and ``T Foo``
> authors: add AND on name_initials_analyzer of firstname

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
ref: cern-sis/issues-inspire#137
> citedby query: use tmp key for recid in terms lookup query

- inspire_query_parser/visitors/elastic_search_visitor.py
- tests/test_elastic_search_visitor.py
ref: https://github.com/cern-sis/issues-inspire/issues/616
> fix(es visitor): Removed unnecessary checking for bai_fieldnames
